#!/bin/bash

set -euo pipefail

cd "$(dirname "$0")"
name="$(basename "$PWD")"
exe="/c/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"
crx="dist/$name.crx"

die() { echo "error: $*" 1>&2; exit 1; }

# Check for uncommitted changes
if [[ -n "$(git status --porcelain)" ]]; then
  die "uncommitted changes"
fi

if [[ "$(git branch --show-current)" != "master" ]]; then
  die "not on the \"master\" branch"
fi

echo "Packing..."
rm -rf dist; md -p dist
git archive --format=tgz --prefix="$name/" master \
  | tar xzf - -C dist

cmd=("$exe")
cmd+=(--pack-extension="$(wslpath -am "dist/$name")")
cmd+=(--pack-extension-key="$(wslpath -am "keys/private.pem")")
"${cmd[@]}"

if [[ ! -e "$crx" ]]; then
  die "Expected CRX file not generated at $crx"
fi
echo "Done: $crx, opening folder"
echo "=> use the $name directory to load unpacked if needed"

open -s "$crx"
